# Generated by Django 4.2.2 on 2023-10-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='admins',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
