# Generated by Django 4.2.2 on 2023-10-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_alter_admins_created_at_alter_admins_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admins',
            table='admins',
        ),
    ]
