# Generated by Django 4.2.2 on 2023-10-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0004_alter_admins_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='password',
            field=models.CharField(max_length=191),
        ),
    ]
